# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               tscheys
tagline:             'Software Engineer'
description:         ''
url:                 
baseurl:             'http://tscheys.github.io/posts'
paginate:            5

# About/contact
author:
  name:              Tim Scheys
  url:               tscheys.github.io
  email:             tim.scheys@gmail.com

# Custom vars
version:             1.0.0
